; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Contacts App"
#define MyAppVersion "0.10"
#define MyAppPublisher "Buldakov"
#define MyAppExeName "ContactsApp.View.exe"
#define AppDate GetDateTimeString('yyyy-mm-dd', '-','-')

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5C214199-1E7F-46E6-B014-13E38CAE9511}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName="{autopf}\Buldakov\Contacts App"
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=Output
OutputBaseFilename=ContactsAppBI_Setup_{#AppDate}
SetupIconFile=..\ContactsApp.View\ContactsApp_96x96.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\ContactsApp.View\bin\Debug\net6.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ContactsApp.View\bin\Debug\net6.0-windows\ContactsApp.Model.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ContactsApp.View\bin\Debug\net6.0-windows\ContactsApp.View.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ContactsApp.View\bin\Debug\net6.0-windows\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ContactsApp.View\bin\Debug\net6.0-windows\ContactsApp.View.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ContactsApp.View\bin\Debug\net6.0-windows\ContactsApp.View.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ContactsApp.View\bin\Debug\net6.0-windows\Newtonsoft.Json.xml"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

